version: ~> 1.0

import:
  - silverstripe/silverstripe-travis-shared:config/provision/standard-jobs-range.yml

jobs:
  include:
    - php: 7.4
      env:
        - DB=MYSQL
        - PHPUNIT_TEST=1
        - CRONTASK=1

before_script:
  - if [[ $CRONTASK ]]; then composer require silverstripe/crontask:^2; fi

